version: '3'
services:

  db:
    build: mongodb+srv://muratalemdr:12345_mm@muratlmdr.0lejv.mongodb.net/dockersanic?retryWrites=true&w=majority


  web:
    build: https://github.com/muratlmdr/sanic_project.git
    depends_on:
      - db


    ports:
      - "8000:8000"

