version: '3'
services:

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/var/lib/mongodb/data

  web:
    build: https://github.com/muratlmdr/sanic_project.git
    depends_on:
      - db
    ports:
      - "8081:8081"
  alerta:
    image: alerta/alerta-web
    volumes:
      - $PWD/config/config.json:/web/config.json
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
volumes:
  db-data: