version: '3'
services:

  db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./db-data:/var/lib/mongodb/data

  web:
    build: https://github.com/muratlmdr/sanic_project.git
    depends_on:
      - db
    ports:
      - "8081:8081"
volumes:
  db-data: